purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8875206
  brandStrength: 1
  lightness: 0.6945059
  brandColors:
    - '#6C5044'
    - '#FFFFFF'
    - '#D2B5A7'
    - '#C57B5A'
    - '#33231D'
  rhythmicContrast: 0.7527571
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: The Legacy Creative
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5747905
layout_spectrum: 0.3085106
