layout_spectrum: 0.7955753
typography_spectrum: 0.5747905
color:
  saturation: 0.8875206
  lightness: 0.6945059
  brandStrength: 0.1150943
  rhythmicContrast: 0.7527571
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: The Legacy Creative
