purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4957447
  brandStrength: 0.4787234
  lightness: 0.4872341
  brandColors:
    - '#212121'
    - '#9FA7B1'
    - '#FEE3C6'
    - '#7C8D95'
    - '#4A4C47'
  rhythmicContrast: 0.493617
analytics:
  twitter: null
  google: null
  facebook: null
name: The Legacy Creative
favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5747905
layout_spectrum: 1
