purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4957447
  brandStrength: 0.4787234
  lightness: 0.4872341
  brandColors:
    - '#0C1526'
    - '#1B3570'
    - '#87A5C9'
    - '#27569E'
    - '#CFD5E1'
  rhythmicContrast: 0.493617
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: The Legacy Creative
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5747905
layout_spectrum: 0
