layout_spectrum: 0.7769588
typography_spectrum: 0.9352794
color:
  saturation: 0.6065433
  lightness: 0.3077972
  brandStrength: 0.410113
  rhythmicContrast: 0.328905
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: The Legacy Creative
